title: "Mi Blog"
description: "Un blog sobre desarrollo web software y tecnologa"
url: "https://serloro.github.io"
baseurl: ""

author:
  name: "serloro"
  email: "tu@email.com"
  github: "https://github.com/serloro"
  twitter: "@serloro"

theme: jekyll-theme-cayman
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

feed:
  path: rss.xml

seo:
  type: Blog
  twitter:
    username: "@serloro"
    card: "summary_large_image"

social_links:
  - name: GitHub
    url: https://github.com/serloro
  - name: Twitter
    url: https://twitter.com/serloro

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
